### ISSUE TITLE
What to call them?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#1]
I went with RSaturday because it's a familiar name, there's already SQLSaturday and SharePoint Saturday out there.

It does have the negative that when it gets shortened like SQLSat that you get a bit of a curse-word in America but with an British accent. Of course, I like humour so I see badges saying "I'm an R-Sat" but this might be taken a bit amiss!

An alternative suggestion was SatRday which is a great pun, in keeping with what we usually do when we name things in the community. This does have it's own problem though - it's a typo of a common word making it's googleability rather low.

So we have 2 candidate names each with negatives, more alternative would be good, or votes either way.

**Comment by philbudden** [comment]
I like SatRday, it's quirky and memorable.  I think the typo issue could also apply (albeit to a lesser extent) for RSat as I see RStats around a lot.

**Comment by stephlocke** [comment]
oo, that's an excellent point about #Rstats, which we use because #r is a crappy hashtag AFAIK

**Comment by ZoeLocke** [comment]
Sat-Arrrrrrrr-Days

**Comment by daroczig** [comment]
+1 for SatRday :)

**Comment by sqldiver** [comment]
I quite like RSat.  It goes well with a catchy logo:

Where's your RSat this weekend?

Certainly has a nice "ring" to it.

**Comment by sqldiver** [comment]
But on a more serious note - it shouldn't have to have Saturday in the title:

RCon
R-ally
LeaRn
Rssembly
DiscovR

But SatRday is also reasonable.

**Comment by stephlocke** [comment]
what about satRDayS - R + data science ?

**Comment by philbudden** [comment]
:ok_hand:

**Comment by SQLThomas** [comment]
Would you call it "SatRdayS London" then, for example? To me that sounds like they always occur in the plural... I guess if you tend to keep the events to the Saturday, my favourite so far would be  "SatRday", yet pronouncing it the "Oz way" ;-)

**Comment by stephlocke** [comment]
Yeah, the Oz way or the highway! 

I'm still vacilating on whether it needs to be anything other than R focused. :-/

**Comment by eddelbuettel** [comment]
> there's already SQLSaturday and SharePoint Saturday 

Both are IMHO largely irrelevant to an R audience.   The name proposals here do not invoke community involvement around R--even in the slightest--so in my book, you are doing yourself a disservice but sticking to a cutesy name.

**Comment by stephlocke** [comment]
Agreed that we don't have to stick with it at all @eddelbuettel :-) 

A big part of why I'm not trying to do this on my own is to ensure it gets broad input from the community - I only know a segment and am heavily influenced by my Microsoft-focused roots. Getting opinions from folks like you is really valuable. So, for me it happening on the weekend is the non - negotiable bit,  everything else is TBC. 

What sort of names /emphasis do you think we should be proposing for these events?

**Comment by eddelbuettel** [comment]
"Naming things" is hard.

**Comment by stephlocke** [comment]
Sans fantastic new suggestions - gonna proceed with satRdays
