### ISSUE TITLE
Who can help?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#11]
We need peeps who can:
- [ ] Organise
- [ ] Build websites
- [ ] Present
- [ ] Sponsor
- [ ] Tweet / blog / promote
- [ ] Build some graphics
- [ ] Attend!
- [ ] Donate a venue

Please volunteer here!

**Comment by philbudden** [comment]
Hi Steph,
Happy to volunteer to help with organisation as well as Tweet / blog / promote and attend of course.

**Comment by ZoeLocke** [comment]
You know I'll help you organise your one @stephlocke, and I'll put myself forward for social media, graphic design and website work

**Comment by daroczig** [comment]
Happy to help with organizing, promoting, attending, findings sponsors and venue, presenting around Los Angeles and Hungary.

**Comment by sqldiver** [comment]
I'm happy to volunteer to help out at an event.

**Comment by jtemporal** [comment]
Hi y'all, would be very happy to help Tweet / blog / promote, Attend (if possible) and maybe help with a venue for events (Ribeirão Preto, São Paulo, Brazil)

**Comment by brennanpincardiff** [comment]
Hi Steph, happy to help organise, present, attend. I might be able to help with venue if Cardiff based. 
Best wishes, P

**Comment by norcalbiostat** [comment]
Add me on as a volunteer to help organize, possibly present & attend if in N. California, and eventually  host an event in Chico CA. (Chico State University) . The R landscape at present is relatively low, but lots of interest and lots of sporadic use across campus and in the community. We are just starting to organize a RUG to develop a more solid community, so I can't see hosting a full event anytime soon, but having a smaller, satellite, type events could be possibly early on.

**Comment by stephlocke** [comment]
:thumbsup:

**Comment by stephlocke** [comment]
Hey folks, anyone able to help spin up and evaluate some open-source conference systems over the next fortnight?

**Comment by daroczig** [comment]
@stephlocke happy to help -- let me know the next steps. Do you want to evaluate some of https://github.com/stephlocke/RSaturday-proposal/issues/6#issuecomment-156027278 or do you have any other candidates?

**Comment by stephlocke** [comment]
There's also a drupal candidate. I'll include the details tomorrow but hitting the ones you found first is great.

**Comment by daroczig** [comment]
Sounds good! Maybe we should move this discussion to #6.

Do you have a host where we can play with these or should I spin up a VPS for this purpose?

**Comment by stephlocke** [comment]
To get an easily consumable list of volunteers and audience, I've made a google survey.

could y'all take the time to fill it in: http://goo.gl/forms/JwfpJ1I1rZ
and ideally RT [me](https://twitter.com/SteffLocke/status/684681348179718144) or tweet about it?

**Comment by john-sandall** [comment]
Happy to help out with organising/promotion/presenting...whatever's needed. I'm based in London.
