### ISSUE TITLE
Should these be technology or capability focused?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#12]
I've been working with a tech-focus, lots of HowTo in R but a number of people have raised a good point - should we be multi-tech and focus on capability e.g. data science or business analytics, instead?

**Comment by philbudden** [comment]
I love learning about new tech but sometimes it's good to put things in context, how would I use this, what could I accomplish with it?

**Comment by ZoeLocke** [comment]
Agreed, both kind of need to go hand in hand. If you're planning on making this a more business oriented R conference then people need to learn the tech, but also the concepts. However, in this situation I'd say people are more likely to already have the capability, and be more interested in the tech

**Comment by stephlocke** [comment]
An interesting point on this is how long will something continue to be relevant? 

The R language is huge and growing, so there's a lot to say and learn, but would something more generic like "data science" enable us to keep going on a shifting technology base. That does of course beg the question, of how long will data science last.

I was just reading an interesting, but unfortunately quite brief, article about [how LISA has been going for 28 years](https://opensource.com/business/15/10/lisa15-interview-amy-rich-mozilla). They focus on a topic Large System Admin, and cover different techs within the conf.

**Comment by SQLShark** [comment]
I really like the idea and it is growing on me more and more. I wonder if you do arrange something then maybe to arrange it with a focus. Analytical languages looking at possibly both R and Python. To add to the "will DS last" I would like to add that I think it will. With any new tech or technique you always have a hype wave and DS is still on that hype wave. However when the initial wave is over you have a plateau which stays. Look at "Big Data" the wave is over and we are left with some really decent tech. DS in 5 years might not be called DS but it will still be there. People need to write smarter processes and DS helps.

**Comment by stephlocke** [comment]
AnaLangs? Practical advice in different analytical languages, sitting somewhere in-between R & DS?

**Comment by SQLShark** [comment]
LOVE that that name! You're the queen of naming projects! Yeah something more open. Maybe I just do not know enough about R to see the legs it has on its own. I think there is much more you can look at with AnaLangs! R, Python, JS and JS libs etc.

**Comment by reddtrain** [comment]
If the plan is to leverage the R Consortium and its funding, I think the emphasis needs to be on R. The capability focus could occupy the same space as the SQL Saturday BI gatherings - useful and important, but built on the established SQL Saturday groups.

**Comment by stephlocke** [comment]
I think if we leave it as satRdays,  R conferences, and let the local organisers set the emphasis based on their local audience and who they would like to pull in. So if they want to grow/emphasise data science they can but if they want to focus on packages and code performance they could do that too. As we grow, we'd then also get some interesting data on what areas garner the most interest.
