### ISSUE TITLE
What R conferences happened in 2015?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#15]
I'd like to compile and include a comprehensive list of R conferences that happened last year.

List includes:
- UseR!, Denmark, ~£400
- EARL London, UK, ~£400
- EARL Boston, USA, ~£400
- R/Finance, USA, ~£200
- R in Insurance, Holland, ~£300
- BioC 2015, USA, [??]
- European Bioconductor Developers' Meeting 2015, UK, [??]

Were there any more, and does anyone know the (industry) cost of the last two events?

**Comment by Ironholds** [comment]
http://china-r.org/ too!

**Comment by hturner** [comment]
New York R conference http://www.rstats.nyc/
Rencontres R (French R meeting) http://r2015-grenoble.sciencesconf.org/?lang=en
New Challenges for Statistical Software - The Use of R in Official Statistics. (R-omania conference) http://r-project.ro/
VII Jornadas de Usuarios de R (7th Meeting of Spanish R Users) http://r-es.org/7jornadasR/
R Programing Language for Data analysis and Statistical Applications (R2015) http://www.sirirajconference.com/conference/sm_index.php?sm_id=126&menu=15
Psychoco 2015 (R-focused psychometrics meeting) http://eeecon.uibk.ac.at/psychoco/2015/index.html
BiocAsia2015 http://www.bioconductor.org/help/course-materials/2015/BiocAsia2015/

Bioc2015 registration was $600, don't know about European (note there were two in 2015, http://www-huber.embl.de/BiocEurope/ and https://sites.google.com/site/eurobioc2015/) - try contacting one of the organisers.

**Comment by daroczig** [comment]
> New Challenges for Statistical Software - The Use of R in Official Statistics. (R-omania conference) http://r-project.ro/

This was 100 EUR as far as I know. cc @markvanderloo

**Comment by markvanderloo** [comment]
Yep. 100 eurobucks indeed.

**Comment by stephlocke** [comment]
I've added most of these now :) still finding some more in China!
