### ISSUE TITLE
Do we want a central platform?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#6]
Conferences can be tough to organise, do we want to build a central platform that will give people the tools out of the box?

The SQLSats have a central platform, that whilst it can be a pain, provides a great interface for organisers, speakers, attendees, and admins.

The downside of a central platform is that it has to be built and maintained - so there'd be cost, time, and the dreaded "users". ;-)

**Comment by ZoeLocke** [comment]
Rather than a platform, perhaps just an open source package that users can fork out and play around with?

**Comment by stephlocke** [comment]
Could have spin up site templates that folks can use, but for the most part organisers won't be web-devs so we'd need to pitch the level of our template just right.

Also, as you know from our trials and tribulations with SQL Relay, putting together you own system(s) for a conference is really time consuming. The SQLSat folks get immediately working stuff that means event organisers just worry about the event and there's a relative few who have to worry about the central infrastructure.  

I think whatever we do decide do, it should be 100% open source so that other communities can contribute and/or utilise it. It's the biggest problem I have with the SQLSat infrastructure is that it's closed source and I can't help make it better.

**Comment by ZoeLocke** [comment]
:+1:

**Comment by daroczig** [comment]
Sorry, I might have missed the thread and posted this at #5, so copying here as well:

> If charging a fee (being discussed at #2), then having a central platform for ticketing and handling money would be very helpful -- using some services like https://sched.org and/or https://www.eventbrite.com might save us a lot of time spent on administration and custom hacks.

**Comment by stephlocke** [comment]
With the other services though, esp if you charge, you start getting a lot of charges that eat your income and organisers have to spend time setting stuff up. It's a bit monolithic but the sqlsat central platform means consistency with ease. 

As well as the open source deliverable that others can utilise, I think doing it  ourselves could mean lower costs for people as they could just use paypal to collect funds.

In my head I have a split between some central folks who develop the platform and provide assistance, and the satRday organisers who deliver confs around the world.

**Comment by daroczig** [comment]
Wow, I've just realized that eventbrite charges 5.5%+1 USD, which is around 7.5% fee for a $50 ticket :O A quick look at meetup.com suggests similarly high fees. Using paypal should be around 3% as far as I know.

But back to the original topic, I found these open-source event/conference manager tools, might be interesting to check:
- https://github.com/osbridge/openconferenceware
- https://pkp.sfu.ca/ocs/

Starting a platform from scratch would require a lot of work.

**Comment by stephlocke** [comment]
I'll take a look at those - I personally think there's a lot of value in a central platform but building our own is less desirable than helping others with their platform or forking a variant. I'm keen that whatever at decide to do we stay open source where possible.

**Comment by stephlocke** [comment]
@daroczig no host, but if you need hosting I can spin up a space on azure or a number of locations

**Comment by stephlocke** [comment]
http://usecod.com/

**Comment by stephlocke** [comment]
Yep- we'll be using the drupal cod system from above

**Comment by daroczig** [comment]
Adding a quick comment here as well on the idea that I've described on Slack previously:
- we can have the central homepage on GH eg at https://github.com/satRdays/satRdays.github.io currently being rendered at http://satRdays.github.io -- which provides general info on the satRdays series and lists all locations
- we can easily create separate pages for the locations by simply forking a template (based on eg the useR! 2014 conf homepage). I've created a quick example at https://github.com/satRdays/budapest2016 rendering at http://satrdays.github.io/budapest2016
- the limitation of this design is that the homepages are static, so we have to outsource CfP and registration:
  - Steph already suggested cfp.io for the prior (which seems to be pretty cool BTW as a central platform)
  - and I've just found https://www.tickettailor.com/pricing for the latter -- so the satRdays org can have a pretty reasonable/low monthly fee and let the orgs collect funds and handle registration + check in easily via Stripe or Paypal without extra fees like at eventbrite, meetup.com etc

What do you think?
