### ISSUE TITLE
How to help beginners?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#8]
@jennybc had a great idea - a beginners workshop that can be run by anyone.

Would we want to make something like that mandatory to the events so that we're also guaranteeing a minimum level of support for newbs? 

I know that some organisers lose sight of the fact that beginners attend and end up bragging about the percentage of 300/400 level sessions they have at their events. Not sure if that's something we'd want to ensure is avoided from day0?

**Comment by philbudden** [comment]
Being fairly new to R myself this is something I'd like to see.  Something that would have helped me is a collaborative workshop.  I read lots of books, watched lots of videos and talked to lots of people but none of this gave me much confidence.  Once I actually started using R I was amazed at how much I could accomplish, it was finding something to work on to practice these skills that was my biggest headache.  It's been a balancing act in work between using R and using less effective methods that I know well and can (at least initially) get results quicker from.

**Comment by reddtrain** [comment]
I think mandating beginner sessions should be avoided -- and I say that as a rank beginner. 

I think they should be strongly encouraged, but in my experience with volunteer organizations, you want to put up as few hurdles as possible. A beginner can still learn something from a 300-level session, even if it wouldn't be as beneficial as a focused beginner session.

**Comment by jtemporal** [comment]
I agree with @reddtrain here. "For begginers" workshops should be encouraged but not mandatory for the more advanced ones.

**Comment by stephlocke** [comment]
Agreed, peeps - so I think we should definitely build a canned workshop, one that could be picked up by anyone to run. Do we want a separate proposal for it's dev or should we run with it as part of satRdays?

**Comment by reddtrain** [comment]
I think that depends on the scope of the beginners' workshop. 

If you're envisioning a 1-2 hour workshop on getting started with R, covering the bare-bones basics, I would think that could stay under the satRdays umbrella. 

If you're seeing a whole day of beginner training, then you should probably separate that into its own project.
1) As a rule, content creation should stay out of the satRday project as much as feasible;
2) Resources on the satRday project would be stretched by having to create that amount of reusable material;
3) A beginner training course would seem to be a slam dunk project for the Consortium;
4) Such a training course could be made self-paced and open-source for free/nominal cost use under the auspices of the Consortium;
5) The Consortium would do well to attempt to leverage existing material from its partner members to accelerate the development of said training. 
===There may need to be a separate spoke of the satRday project to massage material created for a Consortium-sponsored beginner training course into an appropriate format for satRday use.===

**Comment by norcalbiostat** [comment]
Recently I've have been planning to create a collection of beginner tutorials/workshops (things that can be taught in 1-2 hours) that would be available for anyone to use on their own, or to present to others.  
The concept is that I would screen submitted proposals for inclusion based on some "ease of use" and "uniqueness" criteria. It's still in the 'planning' stage as I have only one tutorial to review at this point. My scope was more on the local RUG level, but I agree with all the points made by @reddtrain in that it could still be under the umbrella of satRdays. Even perhaps up to half day workshops. 

I have also been wondering if building a collection like this would be sufficient for its own proposal - but perhaps linked back to its use on satRdays?

**Comment by stephlocke** [comment]
I think one half day workshop would be a good fit, multiples is worth is own proposal! Get it going and we'll link to it, support it, and I'll submit some ideas for workshops and help build them when you're at that stage  :-)

**Comment by stephlocke** [comment]
Someone is picking up the torch for workshops :)
https://github.com/lgatto/SC-ICS-Proposal
