### ISSUE TITLE
What are the goals of the events?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#9]
Putting this proposal via the R Consortium, means that we should be aligning/subscribing to their goals for the R Community, but we should have our own idea of what the goals for the RSats should be - whether it's R Consortium goals verbatim, just a few of them, or another set of friendlier sounding goals.

What should be the aim(s) of the RSats?

**Comment by reddtrain** [comment]
1c. and 1d. sound like the perfect goals to build upon. 

1c. [E]ncourage and increase user adoption, involvement with, and contribution to, the [R] Environment.
1d. [F]acilitate communication and collaboration among users and developers of the [R] Environment[...]

Add on something like "...through low-cost, easily-accessible training events" to 1c and I think you've got a winner. Is there really anything more that a #SatRday organization should be concerned with?
